import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./header/Header";
import { CryptoProvider } from "./@context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CryptoProvider>
        <body className={montserrat.className}>
          <Header />
          <main>{children}</main>
        </body>
      </CryptoProvider>
    </html>
  );
}
